modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="entitycontrol"
version="${file.jarVersion}"
displayName="Entity Control"
authors="XYAT"
description='''
Entity spawn rules, modifiers, reset behavior, break-spawn rules, and testing dummy tools.
'''

[[dependencies.entitycontrol]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.entitycontrol]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.entitycontrol]]
modId="kineticcore"
mandatory=true
versionRange="[26.9.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.entitycontrol]]
modId="jade"
mandatory=false
versionRange="[11.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.entitycontrol]]
modId="curios"
mandatory=false
versionRange="[5.10.0,)"
ordering="AFTER"
side="BOTH"
